config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :users, only: [:show, :index, :edit, :update] do
    resources :bookings, only: [:create, :destroy, :new, :index] do
      member  do
        post 'accept_booking', to: "bookings#accept_booking"
        post 'decline_booking', to: "bookings#decline_booking"
      end
    end
  end

resources :profiles

end

app/models/booking.rb
class Booking < ActiveRecord::Base


  belongs_to :client, class_name: 'User'
  belongs_to :expert, class_name: 'User'


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :demands, class_name: 'Booking', foreign_key: 'client_id'
  has_many :missions, class_name: 'Booking', foreign_key: 'expert_id'

  geocoded_by :address
  before_save :geocode, if: :address_changed?


  def self.find_for_facebook_oauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]  # Fake password for validation
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.picture = auth.info.image
        user.token = auth.credentials.token
        user.token_expiry = Time.at(auth.credentials.expires_at)
      end
  end


  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    if resource.expert == "1"
      user_path(resource)
    else
      super
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @bookings = Booking.where(:user_id)
  end

  def new
    @expert = User.find(params[:user_id])
    @booking = Booking.new(expert: @expert)
  end

  def create
    @expert = User.find(params[:user_id])
    @booking =  Booking.new(booking_params)
    @booking.expert = @expert
    @booking.client = current_user
    @booking.booking_status = "pending"
    if @booking.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user)
  end

  def accept_booking
    @booking = Booking.find(params[:id])
    @booking.booking_status = "accepted"
    @booking.save
    redirect_to user_path(current_user)
  end

  def decline_booking
    @booking = Booking.find(params[:id])
    @booking.booking_status = "declined"
    @booking.save
    redirect_to user_path(current_user)
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.user = @user

    if @booking.update(params[:booking].permit(:user_id, :planned_for))
      flash[:notice] = 'Your booking was updated succesfully'
    else
      render 'edit'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:price, :comments, :planned_for)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]





  def index
    @users = User.all
    @booking = Booking.new
    @address = params[:query_address]
    @users_around = User.near(@address, 50)

    @experts_around = @users_around.select do |user|
      user.expert == '1'
    end
    @list_display = 5
    @experts_around_short = @experts_around.first(@list_display)

    @markers = Gmaps4rails.build_markers(@experts_around) do |expert, marker|
      marker.lat expert.latitude
      marker.lng expert.longitude
      marker.picture ({"url" => "#{view_context.image_url("logo_32.png")}", "width" => 32, "height" => 32})
      marker.infowindow render_to_string(partial: 'users/infowindow', locals: {expert: expert})
    end
  end


  def show
  @user = User.find(params[:id])
  end


  def edit
  @profile = Profile.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  # after_create :create_profile

  def create_profile
  self.profile.create
  end

  private


    def set_user
      @user = User.find(params[:id])
    end



    def users_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Dashboard</h1>
<div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= @user.first_name %>
      <% @user.demands.each do |demand| %>
        <p>Demande a <%= demand.expert.first_name %></p>
        <p>Status: <%= demand.booking_status %></p>
        <p>Commentaires <%= demand.comments %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for([@expert, @booking]) do |f| %>
        <%= f.input :planned_for, label: "A quelle date souhaitez-vous prendre rendez-vous ?" %>
        <%= f.input :price, label: "Quel prix offrez vous pour cette mission?" %>
        <%= f.input :comments, label: "Merci de detailler votre demande (modele, lien vers l'annonce...)" %>
        <%= f.button :submit %>
      <% end %>
   </div>
  </div>
</div>



<script>
$( document ).ready(function() {
  $('.datepicker').datepicker();
}
</script>

app/views/dashboard/dashboard.html.erb
<h3>Status</h3>

<ul id="bookings">
<% @user.bookings.each do |friend| %>
  <li><%= render partial: 'friend', locals: {friend: friend} %></li>
<% end %>
</ul>

<h3>Purchases</h3>
<ul id="purchases">
  <% @user.purchases.each do |purchase| %>
    <li><%= render partial: 'purchase', locals: {purchase: purchase} %></li>
  <% end %>
</ul>


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>


    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="#">Yes</a></li>
            <li><a href="#">No</a></li>
            <li><a href="#">Cancel</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img src="assets/images/muscle_carid_violet.jpg" class="img-responsive" alt="Generic placeholder thumbnail" height="200" width="200">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Biscauto: trouvez un expert auto pres de chez vous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>

  <%= render "shared/navbar" %>

  <%= render 'shared/flashes' %>



    <%= yield %>



    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&sensor=false&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" %>

  <%= javascript_include_tag "application" %>

  <%= yield(:after_js) %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage-hero-module">
    <div class="video-container">
        <div class="filter"></div>
          <form action="users#index" class="col-md-8 offset-2 address-form" role="form">
            <div class="row">
              <div class="form-group col-sm-8 col-sm-offset-2" id="homepage-title">
                <h1>Faites-vous accompagner d'un expert pour acheter votre véhicule d'occasion</h1>
                <input type="text" class="form-control col-sm-8 offset-2" name="query_address" placeholder="Vous cherchez un expert près de ..." id="address-input">
                <button type="submit" class="submit btn btn-lg btn-primary" style="margin:20px;">C'est parti !</button>
              </form>
            </div>
          </div>
        <video autoplay loop class="fillWidth">
            <source src="http://res.cloudinary.com/jbsebrier/video/upload/v1468599962/Happy-Street_tros8y.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="http://res.cloudinary.com/jbsebrier/video/upload/v1468599968/Happy-Street_byoypk.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video>
        <div class="poster hidden">
            <img src="http://res.cloudinary.com/jbsebrier/image/upload/v1468599965/Happy-Street_ntubkw.jpg" alt="">
        </div>
    </div>
</div>

<div class="wrapper" id="homepage-wrapper">
  <div class="row">
    <div class="col-sm-5 col-sm-offset-1 text-center">
      <h2>Achetez bien conseillé !</h2>
      <p>Evitez les arnaques</p>
      <p>Pour votre recherche d'un véhicule d'occasion, faites-vous accompagner d'un expert</p>
      <p>Sachez reconnaître les bonnes affaires et évitez les problèmes après votre achat</p>
      <button class="btn btn-danger">Trouvez un expert</button>
    </div>
    <div class="col-sm-5 text-center">
      <h2>Devenez Biscautteur !</h2>
      <p>Les voitures ca vous connait ?</p>
      <p>Vous voulez partager votre passion dans votre région, tout en arrondissant vos fins de mois ?</p>
      <p>N'hésitez plus et contactez-nous pour rejoindre notre communauté d'experts !</p>
      <button class="btn btn-danger">Contactez-nous</button>
    </div>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/places.js/1/places.min.js"></script>
<script>
  var placesAutocomplete = places({
    container: document.querySelector('#address-input'),
    language: 'fr',
  });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed navbar-<%= controller.controller_name%>">
  <!-- Logo  -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Logo_with_title.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

         <%= image_tag current_user.picture, class: "avatar-bordered dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/_infowindow.html.erb
<div class="infowindow">

  <div class="card-index-map">
    <div class="card-index-user-name"> <b><%= expert.first_name %></b></div>
    <div class="card-index-user-city"> <%= expert.city %></div>
    <div class="card-index-avatar"> <%= image_tag expert.picture, class:"avatar-large" %> </div>
    <div class="card-index-rating">
      <% expert.rating.round.times do %>
        <%= image_tag 'biscauto_logo_small.png', class:"avatar-tiny" %>
      <% end %>
    </div>
    <button class="btn card-index-profile-btn btn-primary" data-toggle="modal" data-target="#profile-modal-<%=expert.id%>">Afficher le profil</button>
    <button class="btn card-index-request-btn btn-danger" data-toggle="modal" data-target="#booking-modal-<%= expert.id %>">Faire une demande</button>
  </div>

</div>

app/views/users/index.html.erb
<script type='text/javascript'>

$(function(){
    $('#show-more').on('click', function(event) {
      console.log('salut');
    });
});

</script>

<div class="container">
<h1> Nos experts à proximité</h1>



  <div class="row">
    <div id="map" class="col-sm-6" style=" height: 600px; margin: 10px;">
    </div>

      <div class="col-sm-5">
      <h2 style="margin-top: 10px">Les plus proches:</h2>
         <% count = 0 %>
         <% @experts_around.each do |expert| %>
           <% count +=1 %>
           <div class="row <%= count > @list_display ? "hidden" : "" %> card-index-row">
            <div class="col-sm-12 card-index">

              <div class="card-index-user-name"> <b><%= expert.first_name %></b></div>
              <div class="card-index-user-city"> <%= expert.city %></div>
              <div class="card-index-avatar"> <%= image_tag expert.picture, class:"avatar-large" %> </div>
              <div class="card-index-rating">
                <% expert.rating.round.times do %>
                  <%= image_tag 'biscauto_logo_small.png', class:"avatar-tiny" %>
                <% end %>
              </div>
              <button class="btn card-index-profile-btn btn-primary" data-toggle="modal" data-target="#profile-modal-<%=expert.id%>">Afficher le profil</button>
              <button class="btn card-index-request-btn btn-danger" data-toggle="modal" data-target="#booking-modal-<%=expert.id%>">Faire une demande</button>
            </div>
          </div>
          <% end %>

        <button id='show-more'> Voir plus de resultats </button>

        </div>
      </div>
    </div>
  </div>
</div>




<% @experts_around.each do |expert| %>
  <!-- modal for the new booking -->
  <div class="modal fade" tabindex="-1" role="dialog" id="booking-modal-<%= expert.id %>">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Créer une demande</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for([expert, @booking]) do |f| %>
          <%= f.input :planned_for, label: "A quelle date souhaitez-vous prendre rendez-vous ?" %>
          <%= f.input :price, label: "Quel prix offrez vous pour cette mission?" %>
          <%= f.input :comments, label: "Merci de detailler votre demande (modele, lien vers l'annonce...)" %>
          <%= f.button :submit %>
          <% end %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <!-- modal for the profile display -->
  <div class="modal fade" tabindex="-1" role="dialog" id="profile-modal-<%= expert.id %>">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"> <%= expert.first_name %></h4>
          <div class="profile-rating">
            <% expert.rating.round.times do %>
              <%= image_tag 'biscauto_logo_small.png', class:"avatar-tiny" %>
            <% end %>
          </div>
        </div>
        <div class="modal-body">
          <p><%= expert.first_name %> se présente :</p>
          <p> <em>"<%= expert.description %>"</em></p>
          <p> <br></p>
          <p> <%= expert.missions.count %> missions à son actif</p>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
      })
  <% end %>
<% end %>

app/views/users/show.html.erb
  <% if @user == current_user %>

  <% unless current_user.expert == "1"%>

     <div class="container">

        <h1>Mes demandes</h1>
        <% current_user.demands.each do |demand| %>
        <div class="card-demand">
        <div class="card-demand-top">

            <div class="card-demand-top-left">
              <% case demand.booking_status %>
                <% when "pending" %>
                  <i class="fa fa-clock-o" aria-hidden="true"></i>
                  <p class="padded-name"><%= demand.booking_status %></p>
                <% when "accepted" %>
                  <i class="fa fa-check-circle-o" aria-hidden="true" style="color: green;"></i>
                  <p class="padded-name"style="color: green;"><%= demand.booking_status %></p>
                <% when "declined" %>
                  <i class="fa fa-times" aria-hidden="true" style="color: red;"></i>
                  <p class="padded-name"  style="color: red;"><%= demand.booking_status %></p>
              <% end %>
            </div>

            <div>
               <%= link_to "Cancel your booking",user_booking_path(current_user, demand), method: :delete, class: "btn btn-danger" %>
            </div>
        </div>

        <div class="card-demand-bottom">
            <div class="card-demand-bottom-left">
              <h3><%= demand.planned_for.strftime( "Rendez vous le %m/%d/%Y  a  %H:%M") %></h3>
             </div>

             <div class="text-center card-demand-bottom-profile">
                <img src="<%= demand.expert.picture %>" alt="" class= "avatar">
                <p class="padded-name"><%= demand.expert.first_name %></p>
             </div>

              <div class="card-demand-bottom-description">
                 <p><%= demand.comments %></p>
              </div>

              <div class="card-demand-bottom-right">
                <h1><%= demand.price%>&euro;</h1>
              </div>

        </div>
      </div>
    <% end %>

    </div>



    <% else%>


    <div class="container">

      <h1>Mes missions</h1>

        <% current_user.missions.where(booking_status: %w(accepted pending)).each do |mission| %>
      <div class="card-demand">
        <div class="card-demand-top">

            <div class="card-demand-top-left">
               <% case mission.booking_status %>
                  <% when "pending" %>
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                    <p><%= mission.booking_status %></p>
                  <% when "accepted" %>
                   <i class="fa fa-check-circle-o" aria-hidden="true"  style="color: green;"></i>
                   <p><%= mission.booking_status %></p>


                <% end %>
            </div>

            <div class="demands-card-items">
              <%= link_to "Accept your booking",accept_booking_user_booking_path(current_user, mission), method: :post, class: "btn btn-success" %>
            </div>

            <div class="demands-card-items">
              <%= link_to "Decline your booking",decline_booking_user_booking_path(current_user, mission), method: :post, class: "btn btn-danger" %>
            </div>
        </div>

        <div class="card-demand-bottom">
            <div class="card-demand-bottom-left">
              <h3><%= mission.planned_for.strftime( "Rendez vous le %m/%d/%Y  a  %H:%M") %></h3>
            </div>

            <div class="text-center card-demand-bottom-profile">
                <img src="<%= mission.client.picture %>" alt="" class= "avatar">
                <p class="padded-name"><%= mission.client.first_name%></p>
            </div>

            <div class="card-demand-bottom-description">
                 <p><%= mission.comments %></p>
            </div>

        </div>
       </div>
      <% end %>
    </div>
  <%end%>
  <%end%>